version: '2'

services:

  db:
    image: ${DB}:latest
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=mediawiki
      - MYSQL_PASSWORD=mwpass
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - sql-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
     - PMA_HOSTS=db
     - PMA_ARBITRARY=1
     - VIRTUAL_HOST=phpmyadmin.mw.dev
  
  web:
    image: webdevops/${PHPORHHVM}-${WEBSERVER}${DOCKERPHPDEV}:${RUNTIMEVERSION}
    environment:
     - WEB_DOCUMENT_ROOT=/var/www/mediawiki
     - VIRTUAL_HOST=mw.dev,web.mw.dev
     - PHP_DEBUGGER=xdebug
     - XDEBUG_REMOTE_AUTOSTART=1
     - XDEBUG_REMOTE_HOST=${IDELOCALHOST}
     - XDEBUG_REMOTE_PORT=9000
     - XDEBUG_REMOTE_CONNECT_BACK=0
     - PHP_IDE_CONFIG=serverName=docker
    depends_on:
     - db
    volumes:
     - "${DOCKER_MW_PATH}:/var/www/mediawiki"
     - ./config/mediawiki:/var/www/mediawiki/.docker:ro
     - ./config/hhvm/php.ini:/etc/hhvm/php.ini
     - ./config/hhvm/server.ini:/etc/hhvm/server.ini
     - ./scripts/wait-for-it.sh:/srv/wait-for-it.sh:ro

  graphite-statsd:
    image: hopsoft/graphite-statsd
    environment:
     - VIRTUAL_HOST=graphite.mw.dev
    volumes:
     - graphite-data:/opt/graphite/storage

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "${DOCKER_MW_PORT}:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    
volumes:
  sql-data:
  graphite-data:
